name: Signal Bot

on:
  schedule:
    - cron: '*/1 * * * *'  # هر ۵ دقیقه یکبار
  workflow_dispatch:       # امکان اجرای دستی

jobs:
  run-signal-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run signal bot
      env:
        BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
        BALE_CHAT_ID: ${{ secrets.BALE_CHAT_ID }}
      run: |
        python signal_bot.py
